This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file ./MainTutorial.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file MainTutorial.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file MainTutorial.acr....done (6 lines written, 0 warnings).
Output written in MainTutorial.acr.
Transcript written in MainTutorial.alg.
